---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wednesday-Adventures
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SumathiD20/Wednesday_Adventures.git
    targetRevision: feature-architecture
    path: Argocd
  destination:
    server: https://kubernetes.default.svc